### ISSUE TITLE
Errors on `go install .`

### ISSUE THREAD

**Issue by theSamPadilla** [protolambda/eth2-val-tools#15]
Seeing some errors on the installation related to package `github.com/herumi/bls-eth-go-binary v1.28.1`.

```
../go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.28.1/bls/cast.go:9:28: undefined: SecretKey
../go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.28.1/bls/cast.go:9:40: undefined: Fr
../go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.28.1/bls/cast.go:13:26: undefined: Fr
../go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.28.1/bls/cast.go:13:31: undefined: SecretKey
../go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.28.1/bls/cast.go:19:28: undefined: PublicKey
../go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.28.1/bls/cast.go:19:40: undefined: G1
../go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.28.1/bls/cast.go:23:26: undefined: G1
../go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.28.1/bls/cast.go:23:31: undefined: PublicKey
../go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.28.1/bls/cast.go:29:23: undefined: Sign
../go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.28.1/bls/cast.go:29:30: undefined: G2
../go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.28.1/bls/cast.go:29:30: too many errors
```

Perhaps version changed or deprecated? All in all, worth revising.

**Comment by theSamPadilla** [comment]
Latest version is `[v1.32.0]`(https://github.com/herumi/bls-eth-go-binary) but I still seeing the same undefined errors.

**Comment by protolambda** [comment]
Which computer architecture and Go version are you using?

It works for me on `x86_64` Linux AMD, Go 1.20.6.

**Comment by theSamPadilla** [comment]
Linux version: `20.04.6 LTS (Focal Fossa)`
Architecture: `x86_64`
Go Version: `go version go1.21.0 linux/amd64`

**Comment by theSamPadilla** [comment]
Tried downgrading my go version to `1.20.7` and still getting same errors.

**Comment by protolambda** [comment]
The Herumi library is a native dependency, this may be causing the compiler errors with undefined types, if your architecture/type somehow isn't supported by it. Maybe you can try bumping the dependency version, and see if newer versions work?

**Comment by protolambda** [comment]
To replace Herumi BLS with a newer better supported BLS library (BLST or Kilic BLS), we need an alternative to `PrivateKeyFromSeedAndPath` from https://github.com/wealdtech/go-eth2-util which depends on https://github.com/wealdtech/go-eth2-types which uses the Herumi BLS types.

**Comment by protolambda** [comment]
Closing this, issue seems stale, BLS library was swapped already and tool should install fine
