### ISSUE TITLE
generated validators lack "path" in their json files

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [protolambda/eth2-val-tools#21]
i noticed that the validators generated by this tool do not have a value for the path field? is there a reason why?

also, is there a way to generate the path? 

output from one of the generated validator's .json file is shown below

![image](https://github.com/protolambda/eth2-val-tools/assets/30082863/b1035d71-2e02-47eb-b2df-a7ae61a06141)

**Comment by protolambda** [comment]
"path" is optional, it's not set here, feel free to submit a PR if it must work different
