### ISSUE TITLE
install as a go module

### ISSUE THREAD

**Issue by kvbik** [protolambda/eth2-val-tools#3]
It would be nice if we can install this software the same way we can with others eg.:

`GO111MODULE=on go get github.com/protolambda/rumor`

Any particular reason why this one we install only from a cloned repo via `go install .`?

**Comment by protolambda** [comment]
Oh just checked, the module name is `eth2-val-tools` instead of `github.com/protolambda/eth2-val-tools`, in the `go.mod` file. I'll fix that. Although I'm hesitant promoting software for ease of installing that's not built for mainnet security.

**Comment by protolambda** [comment]
Updated in: 177418fcbf23117aac4a2709dfeeec64ba15bbef that should fix it

**Comment by kvbik** [comment]
Yes, the module name was the problem. Thx!

As `go get github.com/protolambda/eth2-val-tools@master` works now I am closing this!
