### ISSUE TITLE
Lodestar 0x prefix on secrets path

### ISSUE THREAD

**Issue by dapplion** [protolambda/eth2-val-tools#8]
In legacy version of Lodestar

> The secrets dir has pubkey-named files containing passwords, but the pubkey in the names are encoded without the 0x prefix. The validators-DB dir is unimportant, and can be left empty. This is managed by lodestar.

This is an old bug that has been patched for a while. To drop this legacy code that reads the password from either 0x prefixed or not named files this tool should be updated.

Lodestar can use the exact same logic as Lighthouse or 0x prefix the secret key filename

**Comment by protolambda** [comment]
Fixed in #9 I think. Keeping the directory around for backwards compatibility.

**Comment by dapplion** [comment]
> Fixed in #9 I think. Keeping the directory around for backwards compatibility.

Thank you! :heart:
